previewsEnabled: true
services:  

- type: web
  name: rails
  env: ruby
  buildCommand: ./build.sh
  startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
  branch: prod
  autoDeploy: true
  plan: starter plus
  healthCheckPath: / 
  domains:
  - uxmetrics.com
  envVars: 
  - fromGroup: uxmetrics-com
  - key: DATABASE_URL
    fromDatabase: 
      name: postgres
      property: connectionString
  - key: REDIS_HOSTPORT
    fromService: 
      name: redis
      type: pserv
      property: hostport

- type: worker
  name: sidekiq
  env: ruby
  buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;
  startCommand: bundle exec sidekiq
  branch: prod
  autoDeploy: true
  plan: starter plus  
  envVars: 
  - fromGroup: uxmetrics-com    
  - key: DATABASE_URL
    fromDatabase: 
      name: postgres
      property: connectionString
  - key: REDIS_HOSTPORT
    fromService: 
      name: redis
      type: pserv
      property: hostport  

- type: pserv
  name: redis
  env: docker
  repo: https://github.com/render-examples/redis.git
  plan: starter plus   
  disk: 
    name: data
    mountPath: /var/lib/redis
    sizeGB: 10

databases:
- name: postgres
  plan: standard
  ipAllowList: []

envVarGroups:
- name: uxmetrics-com
  envVars:
  - key: APP_NAME
    value: UX Metrics   
  - key: LOGO_UPLOAD_ENDPOINT
    value: uxmetrics.imgix.net
  - key: SHORTENER_STARTING_KEY_LENGTH
    value: 6
  - key: FULL_APP_DOMAIN
    sync: false        
  - key: FULL_APP_DOMAIN_WITHOUT_PROTOCOL
    sync: false    
  - key: FULL_APP_DOMAIN_WITHOUT_PROTOCOL_OR_PORT
    sync: false            
  - key: POSTMARK_SERVER_TOKEN
    sync: false
  - key: STRIPE_API_KEY
    sync: false 
    previewValue: sk_test_51HTwIfBkaUHJfABOBlK2Do7IxaHVcDaAz84b3vRLqnerrYy2TZ883tyU6povBKUlVoTuKZPzWAaA3eFRL0lLcOAD00yFP9u5He
  - key: SECRET_KEY_BASE
    sync: false   
  - key: PREVIEW_BUILD
    value: false
    previewValue: true