previewsEnabled: true
services:  

- type: web
  name: rails
  env: ruby
  buildCommand: "./build.sh"
  startCommand: "./start.sh"
  afterFirstDeployCommand: "./preview_build_initialization.sh"
  branch: prod
  autoDeploy: true
  plan: starter plus
  healthCheckPath: / 
  domains:
  - uxmetrics.com
  envVars: 
  - fromGroup: uxmetrics-com
  - key: DATABASE_URL
    fromDatabase: 
      name: postgres
      property: connectionString
  - key: REDIS_HOSTPORT
    fromService: 
      name: redis
      type: pserv
      property: hostport
  - key: RAILS_HOST
    fromService: 
      name: rails
      type: web
      property: host      

- type: worker
  name: sidekiq
  env: ruby
  buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;
  startCommand: bundle exec sidekiq
  branch: prod
  autoDeploy: true
  plan: starter plus  
  envVars: 
  - fromGroup: uxmetrics-com    
  - key: DATABASE_URL
    fromDatabase: 
      name: postgres
      property: connectionString
  - key: REDIS_HOSTPORT
    fromService: 
      name: redis
      type: pserv
      property: hostport  
  - key: RAILS_HOST
    fromService: 
      name: rails
      type: web
      property: host

- type: pserv
  name: redis
  env: docker
  repo: https://github.com/render-examples/redis.git
  plan: starter plus   
  disk: 
    name: data
    mountPath: /var/lib/redis
    sizeGB: 10

databases:
- name: postgres
  plan: standard
  ipAllowList: []

envVarGroups:
- name: uxmetrics-com
  envVars:
  - key: APP_NAME
    value: UX Metrics   
  - key: LOGO_UPLOAD_ENDPOINT
    value: uxmetrics.imgix.net
  - key: SHORTENER_STARTING_KEY_LENGTH
    value: 6
  - key: FULL_APP_DOMAIN
    sync: false        
  - key: FULL_APP_DOMAIN_WITHOUT_PROTOCOL
    sync: false    
  - key: FULL_APP_DOMAIN_WITHOUT_PROTOCOL_OR_PORT
    sync: false            
  - key: POSTMARK_SERVER_TOKEN
    value: 0acc429f-194e-4572-8c9b-cd5a2504d6c9
  - key: STRIPE_API_KEY
    sync: false 
    previewValue: sk_test_51HTwIfBkaUHJfABOBlK2Do7IxaHVcDaAz84b3vRLqnerrYy2TZ883tyU6povBKUlVoTuKZPzWAaA3eFRL0lLcOAD00yFP9u5He
  - key: SECRET_KEY_BASE
    sync: false   
    previewValue: 342ce8ad7075d3447ce7ad5eb7ea326a691bd3bb31cf11e537bf97f34067a5345a48cc002a56c5f84c28c8d684cfb779bb435eee7e2908b3409f87cb73527c0
  - key: PREVIEW_BUILD
    value: false
    previewValue: true